name: morig
channels:
  - pytorch
  - pyg
  - defaults
dependencies:
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cycler
  - dbus
  - expat
  - fftw
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libpng
  - libpq
  - libtiff
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - munkres
  - ncurses
  - networkx
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pcre
  - pillow
  - pip
  - ply
  - pycparser
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-louvain
  - pytorch
  - pytz
  - pyyaml
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - threadpoolctl
  - tk
  - toml
  - tornado
  - tqdm
  - typing_extensions
  - urllib3
  - wheel
  - xz
  - yacs
  - yaml
  - zlib
  - zstd
  - pip:
    - torch_geometric
    - torch_scatter
    - torch_cluster
    - absl-py
    - argon2-cffi
    - argon2-cffi-bindings
    - attrs
    - backcall
    - beautifulsoup4
    - bleach
    - cachetools
    - chardet
    - colorlog
    - debugpy
    - decorator
    - defusedxml
    - dominate
    - entrypoints
    - fastjsonschema
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - importlib-metadata
    - importlib-resources
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - lxml
    - mapbox-earcut
    - markdown
    - matplotlib-inline
    - mistune
    - mpmath
    - msgpack
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - oauthlib
    - open3d
    - opencv-python-headless
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - pkgutil-resolve-name
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - pyasn1
    - pyasn1-modules
    - pycollada
    - pyglet
    - pygments
    - pyrsistent
    - pyzmq
    - requests-oauthlib
    - rsa
    - rtree
    - send2trash
    - shapely
    - soupsieve
    - svg-path
    - sympy
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - terminado
    - tinycss2
    - traitlets
    - trimesh
    - wcwidth
    - webencodings
    - werkzeug
    - widgetsnbextension
    - xxhash
    - zipp
